spring:
  application:
    name: catalog-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
server:
  port: 8081

  data:
    mongodb:
      uri: mongodb://localhost:27017/Streaming

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: movieQueue
  serie:
    name: SerieQueue
  catalog:
    name: CatalogQueue

message: CATALOG OK

  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  mvc:
    log-request-details: true

resilience4j:
   circuitbreaker:
      instances:
        movies:
          slidingWindowType: COUNT_Based
          slidingWindowSize: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 3
          registerHealthIndicator: true
          allowHealthIndicatorToFails: false
          automaticTransitionFromOpenToHalfOpenEnabled: true
        series:
          slidingWindowType: COUNT_Based
          slidingWindowSize: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 3
          registerHealthIndicator: true
          allowHealthIndicatorToFails: false
          automaticTransitionFromOpenToHalfOpenEnabled: true
      retry:
        instances:
          movies:
            waitDuration: 1000
            maxAttempts: 3
            retryExceptions:
              - feign.FeignException$InternalServerError
          series:
            waitDuration: 1000
            maxAttempts: 3
            retryExceptions:
              - feign.FeignException$InternalServerError

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

